package com.couplefox.shared.domain.usecase

import com.couplefox.shared.data.repository.MessageRepository
import com.couplefox.shared.domain.model.Message
import kotlinx.datetime.Clock

class SendMessageUseCase(
    private val messageRepository: MessageRepository
) {
    suspend operator fun invoke(
        senderId: String,
        receiverId: String,
        content: String
    ): Result<Message> {
        val message = Message(
            id = "", // Will be generated by the server
            senderId = senderId,
            receiverId = receiverId,
            content = content,
            timestamp = Clock.System.now()
        )
        return messageRepository.sendMessage(message)
    }
}
